### PR TITLE
added webhook for grafana 4.0 alerting

### PR DESCRIPTION
**Pull request by msupino**
See #203

### CODE REVIEW

**Comment by msupino** [comment]
added.. passes py2.7 tests, fails on 3.x, ill need to setup an env for testing on 3.x

**Comment by satterly** [comment]
I'm not against integrating Alerta with Grafana however I'm not sure it's ready for prime-time yet.
There seems to be very limited amount of information passed in the webhook and this makes generating meaningful alerts extremely difficult.

For example, is it possible to determine what resource/host/service the alert relates to?

Some other questions/issues raised by others would go a long way to improving things...
  * Alerting: Rule Category / Tags? grafana/grafana#6552
  * Include opentsdb tag name values in alert body grafana/grafana#6808
  * Add message in the webhook request grafana/grafana#6725

Thoughts?

**Comment by colomboipl** [comment]
Any news ?

**Comment by satterly** [comment]
Hi @colomboipl I've not heard back from @msupino yet. Do you have an opinion?

**Comment by msupino** [comment]
This might not be the best implementation for grafana, but it's a start,
and can be enhanced later, grafana is not host centric, a graph can be made
from different sources.. let's see if it can be used for real grafana
implementation, mine isn't really in use, but others might have better
reference

**Comment by satterly** [comment]
Sounds reasonable. Merging this, then and will refactor (slightly) and fix tests in following PR.

**Pull request merged**
