### PR TITLE
All users can manage alert blackouts

### PR DESCRIPTION
**Pull request by satterly**
>currently only admin users can create blackouts, would it be possible to make this available to regular users?

/cc @ramshankarjaiswal

### CODE REVIEW

**Comment by ramshankarjaiswal** [comment]
I've just tested this, regular users still cannot see the blackout option in the alerta user interface.

**Comment by satterly** [comment]
You're right. I thought I made the web UI change as well but don't see it. I'll take a look.

**Comment by ramshankarjaiswal** [comment]
Thanks!

**Comment by satterly** [comment]
Web UI updated to support user blackouts.

**Pull request merged**
